In [13]:
import numpy as np
from numpy import linalg as LA
import sympy as sympy 

import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

In [16]:
M = np.array([[-1,0],[0,-2]])
M

array([[-1,  0],
       [ 0, -2]])

In [22]:
I, S = LA.eig(M)
I

array([-1., -2.])

In [2]:
T = np.array([[1,1],[2,5]])
A = np.array([[0,1],[-10,-7]])
T_inv = LA.inv(T)
T_inv

array([[ 1.66666667, -0.33333333],
       [-0.66666667,  0.33333333]])

In [3]:
D = np.matmul(T,np.matmul(A, T_inv))

In [4]:
D

array([[-12.66666667,   1.33333333],
       [-61.33333333,   5.66666667]])

In [5]:
I, S= LA.eig(A)

In [6]:
I

array([-2., -5.])

In [7]:
eig_vect = np.array([[1,-2],[-1,5]])

In [8]:
#creates diaganal matrix with values t_1 and t_2
t_1 = sympy.Symbol('t_1')
t_2 = sympy.Symbol('t_2')
t = np.array([[t_1],[t_2]])
t_mat = np.eye(2) * t
t_mat

array([[1.0*t_1, 0],
       [0, 1.0*t_2]], dtype=object)

In [10]:
S

array([[ 0.4472136 , -0.19611614],
       [-0.89442719,  0.98058068]])

In [11]:
S*10

array([[ 4.47213595, -1.96116135],
       [-8.94427191,  9.80580676]])

In [12]:
S[1:2,0:1] / S[0:1,0:1]  

array([[-2.]])