In [94]:
import numpy as np
from numpy import linalg as LA
import sympy as sympy 

import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

In [95]:
T = np.array([[1,1],[2,5]])
A = np.array([[0,1],[-10,-7]])
T_inv = LA.inv(T)
T_inv

array([[ 1.66666667, -0.33333333],
       [-0.66666667,  0.33333333]])

In [96]:
D = np.matmul(T,np.matmul(A, T_inv))

In [97]:
D

array([[-12.66666667,   1.33333333],
       [-61.33333333,   5.66666667]])

In [98]:
I, S= LA.eig(A)

In [99]:
I

array([-2., -5.])

In [100]:
eig_vect = np.array([[1,-2],[-1,5]])

In [110]:
#creates diaganal matrix with values t_1 and t_2
t_1 = sympy.Symbol('t_1')
t_2 = sympy.Symbol('t_2')
t = np.array([[t_1],[t_2]])
t_mat = np.eye(2) * t
t_mat

array([[1.0*t_1, 0],
       [0, 1.0*t_2]], dtype=object)

In [112]:
D = np.matmul(T,np.matmul(t_mat, T_inv))

TypeError: Object arrays are not currently supported

In [103]:
S

array([[ 0.4472136 , -0.19611614],
       [-0.89442719,  0.98058068]])

In [65]:
S*10

array([[ 4.47213595, -1.96116135],
       [-8.94427191,  9.80580676]])

In [70]:
S[1:2,0:1] / S[0:1,0:1]  

array([[-2.]])